apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: aksprod
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      serviceAccountName: portfolio-sa
      containers:
      - name: portfolio
        image: reactportfolio.azurecr.io/my-portfolio:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      imagePullSecrets:
        - name: regcred
---
