apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-sa
  namespace: aksprod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-role
  namespace: aksprod
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-rolebinding
  namespace: aksprod
subjects:
  - kind: ServiceAccount
    name: portfolio-sa
    namespace: aksprod
roleRef:
  kind: Role
  name: portfolio-role
  apiGroup: rbac.authorization.k8s.io 