apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: aksprod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: portfolio 